/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a5_t1_ochoaulises;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Uli Gibson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    public static DB_MySQL myDB = new DB_MySQL();
    
    public Principal() {
        initComponents();
        this.setTitle("Videojuegos - Menú principal");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/iconoX.png")).getImage());
        
        if(myDB.conect())
        {
            lblEstado.setText("CONECTADO");
            lblEstado.setForeground(new Color(13,131,223)); //32, 183, 0
            updateContador();
        }
        

    }
    
    
    private AcercaDe vAcerca = new AcercaDe();
    
    public static void updateContador()
    {
        lblContador.setText(String.valueOf(myDB.count()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReg = new javax.swing.JButton();
        imgNuevoJuego = new javax.swing.JLabel();
        imgBuscarJuego = new javax.swing.JLabel();
        btnBus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenArchivo = new javax.swing.JMenu();
        jmenBuscar = new javax.swing.JMenuItem();
        jmenRegistrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenSalir = new javax.swing.JMenuItem();
        jMenAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnReg.setBackground(new java.awt.Color(133, 194, 255));
        btnReg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReg.setText("REGISTRAR NUEVO");
        btnReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        imgNuevoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/newGame.png"))); // NOI18N
        imgNuevoJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgNuevoJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgNuevoJuegoMouseClicked(evt);
            }
        });

        imgBuscarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchIcon.png"))); // NOI18N
        imgBuscarJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgBuscarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBuscarJuegoMouseClicked(evt);
            }
        });

        btnBus.setBackground(new java.awt.Color(133, 194, 255));
        btnBus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBus.setText("BUSCAR");
        btnBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ESTADO DB:");

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(252, 51, 51));
        lblEstado.setText("NO CONECTADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(imgNuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgBuscarJuego)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(btnBus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgNuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBuscarJuego))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReg)
                    .addComponent(btnBus))
                .addGap(43, 43, 43))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Videojuegos en la base de datos:");

        lblContador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContador.setForeground(new java.awt.Color(0, 142, 255));
        lblContador.setText("0");
        lblContador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContadorMouseClicked(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        label1.setText("¿Qué desea hacer?");

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jmenArchivo.setText("Archivo");

        jmenBuscar.setText("Buscar");
        jmenBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenBuscarActionPerformed(evt);
            }
        });
        jmenArchivo.add(jmenBuscar);

        jmenRegistrar.setText("Registrar nuevo");
        jmenRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenRegistrarActionPerformed(evt);
            }
        });
        jmenArchivo.add(jmenRegistrar);
        jmenArchivo.add(jSeparator1);

        jmenSalir.setText("Salir");
        jmenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenSalirActionPerformed(evt);
            }
        });
        jmenArchivo.add(jmenSalir);

        jMenuBar1.add(jmenArchivo);

        jMenAcercaDe.setText("Acerca de");
        jMenAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenAcercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContador)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblContador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        if(lblEstado.getText().equals("CONECTADO")) Videojuegos.mostrarVentana(1);
        else                                        JOptionPane.showMessageDialog(null, "Acción no permitida, no se pudo conectar a la base de datos", "Videojuegos - Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusActionPerformed
        // TODO add your handling code here:
        Videojuegos.mostrarVentana(2);
    }//GEN-LAST:event_btnBusActionPerformed

    private void imgNuevoJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgNuevoJuegoMouseClicked
        // TODO add your handling code here:
        btnRegActionPerformed(null);
    }//GEN-LAST:event_imgNuevoJuegoMouseClicked

    private void imgBuscarJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBuscarJuegoMouseClicked
        // TODO add your handling code here:
        btnBusActionPerformed(null);
    }//GEN-LAST:event_imgBuscarJuegoMouseClicked

    private void lblContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContadorMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_lblContadorMouseClicked

    private void jMenAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenAcercaDeMouseClicked
        // TODO add your handling code here:
        if(!vAcerca.isShowing())   vAcerca.setVisible(true);
        else                    vAcerca.toFront();
        vAcerca.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenAcercaDeMouseClicked

    private void jmenRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenRegistrarActionPerformed
        // TODO add your handling code here:
        btnRegActionPerformed(null);
    }//GEN-LAST:event_jmenRegistrarActionPerformed

    private void jmenBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenBuscarActionPerformed
        // TODO add your handling code here:
        btnBusActionPerformed(null);
    }//GEN-LAST:event_jmenBuscarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String ObjButtons[] = {"Salir","No salir"};
        int PromptResult = JOptionPane.showOptionDialog(null, 
            "¿Seguro que quieres salir?", this.getTitle()+" - Aviso", 
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, 
            ObjButtons,ObjButtons[1]);
        if(PromptResult==0)
        {
          System.exit(0);          
        }
    }//GEN-LAST:event_formWindowClosing

    private void jmenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenSalirActionPerformed
        // TODO add your handling code here:
        formWindowClosing(null);
    }//GEN-LAST:event_jmenSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel imgBuscarJuego;
    private javax.swing.JLabel imgNuevoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenAcercaDe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmenArchivo;
    private javax.swing.JMenuItem jmenBuscar;
    private javax.swing.JMenuItem jmenRegistrar;
    private javax.swing.JMenuItem jmenSalir;
    private java.awt.Label label1;
    public static javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblEstado;
    // End of variables declaration//GEN-END:variables
}
